name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches:
      - master


jobs:
  test:
    name: Run tests on python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8', '3.9', '3.10']
        include:
          - python: '3.8'
            toxenv: 'py38'
          - python: '3.9'
            toxenv: 'py39'
          - python: '3.10'
            toxenv: 'py310'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python }}

      - name: Prepare test env
        run: python -m pip install -U tox coveralls

      - name: Test
        run: TOXENV=${{ matrix.toxenv }} tox

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{ matrix.python }}
          parallel: true
          path-to-lcov: .coverage

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
